"""add table

Revision ID: d26f076d413c
Revises: 
Create Date: 2023-05-21 23:13:56.099796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26f076d413c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('primary_location_country', sa.String(), nullable=True),
    sa.Column('primary_location_city', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('company_type', sa.String(), nullable=True),
    sa.Column('years_experience_industry', sa.Integer(), nullable=True),
    sa.Column('years_experience_company', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_ladder', sa.String(), nullable=True),
    sa.Column('job_level', sa.String(), nullable=True),
    sa.Column('required_hours_per_week', sa.String(), nullable=True),
    sa.Column('actual_hours_per_week', sa.String(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('tota_base_salary', sa.Integer(), nullable=True),
    sa.Column('total_bonus', sa.Integer(), nullable=True),
    sa.Column('total_stock_options_equity', sa.Integer(), nullable=True),
    sa.Column('health_insurance_offered', sa.String(), nullable=True),
    sa.Column('annual_vacation_weeks', sa.String(), nullable=True),
    sa.Column('is_happy_at_current_position', sa.String(), nullable=True),
    sa.Column('has_plan_to_resign', sa.String(), nullable=True),
    sa.Column('thoughts_about_industry_direction', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('necessary_top_skills', sa.String(), nullable=True),
    sa.Column('has_done_bootcamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_survey')
    # ### end Alembic commands ###
